---
- name: Deploy dotfiles
  hosts: local

  pre_tasks:
    - name: Update cache of package manager
      become: true
      ansible.builtin.package:
        update_cache: true
        upgrade: true

    - name: Gather package facts
      become: true
      ansible.builtin.package_facts:
        manager: auto

  roles:
    - desktop
    - development
    - terminal
    - tools
