---
- name: Install onefetch
  become: true
  ansible.builtin.package:
    name: onefetch
    state: present

- name: Enable repository greeter
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: "### {mark} enable respository greeter for onefetch ###"
    block: |
      last_repository=
      check_directory_for_new_repository() {
        current_repository=$(git rev-parse --show-toplevel 2> /dev/null)
        
        if [ "$current_repository" ] && \
          [ "$current_repository" != "$last_repository" ]; then
          onefetch
        fi
        last_repository=$current_repository
      }
      cd() {
        builtin cd "$@"
        check_directory_for_new_repository
      }

      # optional, greet also when opening shell directly in repository directory
      # adds time to startup
      check_directory_for_new_repository
