---
- name: Install zoxide
  become: true
  ansible.builtin.package:
    name: zoxide
    state: present

- name: Setup zoxide
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: "### {mark} setup zoxide ###"
    block: |
      eval "$(zoxide init bash)"
  when: check.found == 0
